### ISSUE TITLE
Zap Tool error

### ISSUE THREAD

**Issue by ballsyst** [seqzap/ni-xnet-dot-net#2]
Is this suppose to be stand alone or is it still connected to the code for SeqZap. I get this error win trying to run
![image](https://user-images.githubusercontent.com/70712252/92137400-138f4a80-eddb-11ea-9a95-1c5698170e27.png)

**Comment by rasmus-toftdahl-olesen** [comment]
Hi, i do not think it should be connected to SeqZap - but i do not maintain
the project anymore.

It looks like you are trying to execute a "DLL".

**Comment by ballsyst** [comment]
I was just trying to run example not DLL

Sent from Yahoo Mail on Android 
 
  On Fri, Sep 4, 2020 at 1:37 AM, Rasmus Toftdahl Olesen<notifications@github.com> wrote:   

Hi, i do not think it should be connected to SeqZap - but i do not maintain
the project anymore.

It looks like you are trying to execute a "DLL".

**Comment by rasmus-toftdahl-olesen** [comment]
Hmm, it might be the output path that is hardcoded to somewhere inside
SeqZap (to make development easier).

You are very welcome to submit a patch where the path is fixed to
something more sane like "output" inside the root of the workspace.
